spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  mvc:
    hidden method:
      filter:
        enabled: true
